### ISSUE TITLE
net9 rc3: Could not inflate Behavior subclass com.google.android.material.bottomsheet.BottomSheetBehavior

### ISSUE THREAD

**Issue by softlion** [the49ltd/The49.Maui.BottomSheet#137]
I upgraded a project to net9 rc3, and when trying to display the bottom sheet,
it is crashing with that message:

```
`the49_maui_bottom_sheet_design: Could not inflate Behavior subclass com.google.android.material.bottomsheet.BottomSheetBehavior`
```

Any idea how to workaround or fix ?

Using an android simulator Pixel5 API 34, and a maui app

related stack trace:
```
   at Android.Views.View.Inflate(Context context, Int32 resource, ViewGroup root) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net9.0/android-35/mcw/Android.Views.View.cs:line 17974
   at The49.Maui.BottomSheet.BottomSheetController.EnsureWindowContainer()
   at The49.Maui.BottomSheet.BottomSheetController.Show(Boolean animated)
   at The49.Maui.BottomSheet.BottomSheetManager.PlatformShow(Window window, BottomSheet sheet, Boolean animated)
   at The49.Maui.BottomSheet.BottomSheetManager.Show(Window window, BottomSheet sheet, Boolean animated)
   at The49.Maui.BottomSheet.BottomSheet.ShowAsync(Window window, Boolean animated)
```

**Comment by softlion** [comment]
Fixed here: https://github.com/softlion/The49.Maui.BottomSheet

**Comment by SoureMaster** [comment]
Looks like there are compatiblity issues.

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	NU1202	Package Vapolia.The49.Maui.BottomSheet 8.0.4-ci-11723878490 is not compatible with net9.0-maccatalyst18.0 (.NETCoreApp,Version=v9.0) / android-arm64. Package Vapolia.The49.Maui.BottomSheet 8.0.4-ci-11723878490 supports:
  - net8.0-android34.0 (.NETCoreApp,Version=v8.0)
  - net8.0-ios18.0 (.NETCoreApp,Version=v8.0)
  - net9.0-android35.0 (.NETCoreApp,Version=v9.0)
  - net9.0-ios18.0 (.NETCoreApp,Version=v9.0)	DTL.Main (net9.0-android)

**Comment by softlion** [comment]
Bottom sheet has never supported maccatalyst so I removed the tfm. 

Remove maccatalyst from your targets.

**Comment by Thibault-Vellicus** [comment]
Hello.
Thanks to @softlion for the fix. 
Will this fix be merged into the main branch?

**Comment by SlavomirDev** [comment]
The previous suggested solution did not help me...

I managed to solve the problem easier.:
If you do Fork with the repository, then specify the following in the EnsureWindowContainer method in the BottomSheetController class:

```
void EnsureWindowContainer()
{
    EnsureStayOnFrontView(_mauiContext.Context);
    if (_windowContainer is null)
    {
        var container = default(FrameLayout);
        if (OperatingSystem.IsAndroidVersionAtLeast(35))
        {
            container = new FrameLayout(_mauiContext.Context)
            {
                LayoutParameters = new FrameLayout.LayoutParams(FrameLayout.LayoutParams.MatchParent, FrameLayout.LayoutParams.MatchParent)
            };

            var coordinatorLayout = new CoordinatorLayout(_mauiContext.Context)
            {
                LayoutParameters = new FrameLayout.LayoutParams(FrameLayout.LayoutParams.MatchParent, FrameLayout.LayoutParams.MatchParent)
            };

            container.AddView(coordinatorLayout);

            _frame = new FrameLayout(_mauiContext.Context, null, Resource.Style.The49_Maui_BottomSheet_BottomSheetDialog)
            {
                LayoutParameters = new CoordinatorLayout.LayoutParams(FrameLayout.LayoutParams.MatchParent, FrameLayout.LayoutParams.WrapContent)
                {
                    Behavior = new BottomSheetBehavior()
                }
            };
            _frame.SetForegroundGravity(GravityFlags.CenterHorizontal | GravityFlags.Top);
            coordinatorLayout.AddView(_frame);
        }
        else
        {
            container = (FrameLayout)AView.Inflate(_mauiContext.Context, Resource.Layout.the49_maui_bottom_sheet_design, null);
            _frame = (FrameLayout)container.FindViewById(Resource.Id.design_bottom_sheet);
        }

        container.ViewAttachedToWindow += ContainerAttachedToWindow;
        container.ViewDetachedFromWindow += ContainerDetachedFromWindow;

        _windowContainer = new BottomSheetContainer(_mauiContext.Context, container);
        _windowContainer.Backdrop.Click += BackdropClicked;

        _frame.OutlineProvider = ViewOutlineProvider.Background;
        _frame.ClipToOutline = true;

        ViewCompat.SetOnApplyWindowInsetsListener(_windowContainer, new EdgeToEdgeListener(this));
        ViewCompat.SetWindowInsetsAnimationCallback(_frame, new BottomSheetInsetsAnimationCallback(this));

        _behavior = BottomSheetBehavior.From(_frame);

        var callback = new BottomSheetCallback(_sheet);
        callback.StateChanged += Callback_StateChanged;
        _behavior.AddBottomSheetCallback(callback);
    }
}
```

And also add style.xml into Resources/values folder:

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
	<style name="The49.Maui.BottomSheet.BottomSheetDialog" parent="ThemeOverlay.MaterialComponents.BottomSheetDialog">
		<item name="android:navigationBarColor">@android:color/transparent</item>
	</style>
</resources>
```

But it works only for android. If you have some issues from other platforms - this fix may not help

**Comment by peruchali** [comment]
See workaround at https://github.com/the49ltd/The49.Maui.BottomSheet/pull/153
