### ISSUE TITLE
Exception on iOS .Net 9

### ISSUE THREAD

**Issue by trondwa** [the49ltd/The49.Maui.BottomSheet#145]
The49 BottomSheet has worked just fine in my MAUI project using .Net 8 on both iOS and Android for several months.
Last week I upgraded to .Net 9. The BottomSheet works as before on Android. However, on iOS I get an exception. I've tried to create an empy project only with this controller as well, but still no luck.

My code:

            var page = new BottomPage();

            page.HasBackdrop = true;
            page.CornerRadius = 10;

            var detent = new RatioDetent
            {               
                Ratio = 0.5F,
                BindingContext = page,
                IsEnabled = true,
                IsDefault = true
            };
            page.Detents.Add(detent);

            try
            {
                page.ShowAsync(Window);   //The exception happens here
            }
            catch (Exception ex)
            {

                throw;
            }

Exception: Object reference not set to an instance of an object.

Stacktrace:
  at The49.Maui.BottomSheet.BottomSheetHandler.PlatformMapSelectedDetent(BottomSheet view)
   at The49.Maui.BottomSheet.BottomSheetHandler.MapSelectedDetent(BottomSheetHandler handler, BottomSheet view)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[The49.Maui.BottomSheet.BottomSheet, The49.Maui.BottomSheet, Version=8.0.4.0, Culture=neutral, PublicKeyToken=null],[The49.Maui.BottomSheet.BottomSheetHandler, The49.Maui.BottomSheet, Version=8.0.4.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.set_Handler(IViewHandler value)
   at The49.Maui.BottomSheet.BottomSheet.ShowAsync(IWindow parent, Boolean animated, Boolean aboveEverything)
   at Skandia.BottomSheetTest.Pages.MainPage.Button_Clicked(Object sender, EventArgs e) in C:\Source\Skandia.BottomSheetTest\Pages\MainPage.xaml.cs:line 35

Anyone experiencing the same? Someone with a solution?

**Comment by imadofficial** [comment]
Yes, i'm experiencing the same issues.

**Comment by trondwa** [comment]
> Yes, i'm experiencing the same issues.

Ok. And I assume you didn't find a solution? Too bad as I really like the Bottomsheet component.

**Comment by imadofficial** [comment]
Not really, i'm currently experimenting with https://github.com/softlion/The49.Maui.BottomSheet to see if i can get it to work somehow

**Comment by trondwa** [comment]
> Not really, i'm currently experimenting with https://github.com/softlion/The49.Maui.BottomSheet to see if i can get it to work somehow

Let me know if you make it :)
Looked briefly at the isses on that one and unfortunately it seems like there's trouble with iOS there as well.

**Comment by johncdoherty** [comment]
Just a thought, but have you tried calling `ShowAsync` without the `Window` argument: `page.ShowAsync(Window);`? I currently have this approach working in .NET 8 and 9 projects

**Comment by alperen-eker-tatko** [comment]
`using System.Reflection;
using Microsoft.Maui.Handlers;
using The49.Maui.BottomSheet;
using UIKit;

namespace WiseV2.Maui.Platforms.iOS;

public static class BottomSheetFix
{
    public static void ApplyFix()
    {
        try
        {
            // Kütüphanenin DismissAsync komutunu kendi güvenli metodumuzla değiştiriyoruz
            BottomSheetHandler.CommandMapper.ReplaceMapping<BottomSheet, BottomSheetHandler>(nameof(BottomSheet.DismissAsync), (handler, view, request) =>
            {
                try
                {
                    var animated = (request is bool b) ? b : true;
                    
                    // Yansıma (Reflection) ile kütüphanenin içindeki Controller ve NotifyDismissed metotlarına ulaşıyoruz
                    // Not: view.Controller (iOS-specific internal property)
                    var controllerProp = view.GetType().GetProperty("Controller", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public);
                    var notifyMethod = view.GetType().GetMethod("NotifyDismissed", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public);
                    
                    if (controllerProp == null || notifyMethod == null)
                    {
                        // Reflection başarısız oldu, varsayılan davranışı kullan
                        System.Diagnostics.Debug.WriteLine("BottomSheetFix: Reflection failed, using default behavior");
                        return;
                    }
                    
                    var controller = controllerProp.GetValue(view) as UIViewController;

                    if (controller != null)
                    {
                        controller.DismissViewController(animated, () =>
                        {
                            try
                            {
                                // CRASH FIX: Sadece Parent null değilse NotifyDismissed çağır
                                // Parent null ise zaten Dismiss Delegate tarafından temizlik yapılmıştır
                                if (view.Parent != null)
                                {
                                    notifyMethod?.Invoke(view, null);
                                }
                            }
                            catch (Exception ex)
                            {
                                // NotifyDismissed çağrısı başarısız oldu, sessizce geç
                                System.Diagnostics.Debug.WriteLine($"BottomSheetFix: NotifyDismissed failed: {ex.Message}");
                            }
                        });
                    }
                    else
                    {
                        // Controller yoksa (zaten kapalı veya Android vb.), varsayılan davranışı çalıştır veya sessizce geç
                        try
                        {
                            if (view.Parent != null)
                            {
                                notifyMethod?.Invoke(view, null);
                            }
                        }
                        catch (Exception ex)
                        {
                            // NotifyDismissed çağrısı başarısız oldu, sessizce geç
                            System.Diagnostics.Debug.WriteLine($"BottomSheetFix: NotifyDismissed failed (no controller): {ex.Message}");
                        }
                    }
                }
                catch (Exception ex)
                {
                    // BottomSheetFix içinde exception oluşursa, sessizce geç
                    System.Diagnostics.Debug.WriteLine($"BottomSheetFix: Exception in ReplaceMapping: {ex.Message}");
                }
            });
        }
        catch (Exception ex)
        {
            // ApplyFix başarısız olursa, uygulamayı durdurmadan devam et
            System.Diagnostics.Debug.WriteLine($"BottomSheetFix.ApplyFix failed: {ex.Message}");
        }
    }
}
`
**AppDelegate.cs**
**FinishedLaunching**
`                WiseV2.Maui.Platforms.iOS.BottomSheetFix.ApplyFix();
`
