### ISSUE TITLE
[iOS] Dismissing a sheet may cause System.NullReferenceException

### ISSUE THREAD

**Issue by MarcAlx** [the49ltd/The49.Maui.BottomSheet#94]
Observed on 8.0.2 version. This happen occasionally when dismissing a sheet programmatically or via gesture.

Observed on iOS 17.2 (simulator).

For reference here's the underlaying exception:

```
 *** Terminating app due to uncaught exception 'System.NullReferenceException', reason: 'Object reference not set to an instance of an object. (System.NullReferenceException)
   at The49.Maui.BottomSheet.BottomSheet.NotifyDismissed()
   at ObjCRuntime.Trampolines.SDAction.Invoke(IntPtr block) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/ObjCRuntime/Trampolines.g.cs:line 17012
   at UIKit.UIViewController.DismissViewController(Boolean animated, Action completionHandler) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/UIKit/UIViewController.g.cs:line 396
   at The49.Maui.BottomSheet.BottomSheetHandler.Dismiss(BottomSheet view, Object request)
   at The49.Maui.BottomSheet.BottomSheetHandler.MapDismiss(BottomSheetHandler handler, BottomSheet view, Object request)
   at Microsoft.Maui.CommandMapper`2.<>c__DisplayClass6_0[[The49.Maui.BottomSheet.BottomSheet, The49.Maui.BottomSheet, Version=8.0.2.0, Culture=neutral, PublicKeyToken=null]
```

**Comment by Frizbi22** [comment]
I am having the same problem

**Comment by Frizbi22** [comment]
It's possible that the DismissAsync method is being invoked even though the sheet has already been dismissed. This was the problem in my case. Now it is working

**Comment by MarcAlx** [comment]
> It's possible that the DismissAsync method is being invoked even though the sheet has already been dismissed. This was the problem in my case. Now it is working

This also seems to be the source of the problem in my case. 

This would happen when user dismiss sheet via gesture then your code logic triggers a programmatic dismiss via `DismissAsync`. One way to identify if a `DismissAsync` call is needed is to check if `BottomSheet.Window` is not null.
